# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonMkStone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auptime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='watch',
            field=models.IntegerField(default=1437),
        ),
        migrations.AlterField(
            model_name='qa',
            name='qtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='res',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='res',
            name='prow',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='res',
            name='uptime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
