# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PythonMkStone', '0002_auto_20170323_0511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
